config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Authorization Required" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :github, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <% form.label :first_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name"%>
  </div>

  <div class="mb-3">
    <% form.label :last_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="mb-3">
    <% form.label :email, style: "display: block", class:"form-label" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="mb-3">
    <% form.label :phone, style: "display: block", class:"form-label" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="mb-3">
    <% form.label :instagram, style: "display: block", class:"form-label" %>
    <%= form.text_field :instagram, class:"form-control", placeholder:"Instagram" %>
  </div>

  <div class="mb-3">
    <% form.label :github, style: "display: block", class:"form-label" %>
    <%= form.text_field :github, class:"form-control", placeholder:"Github" %>
  </div>

  <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: "hidden"%>

  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.instagram %></td>
    <td><%= friend.github %></td>
    <td><%= link_to 'Show', friend %></td>
</div>

app/views/friends/edit.html.erb
<h1>Edit friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary"%>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<div id="friends">
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Instagram</th>
        <th>Github</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user_id == current_user.id %>
          <%= render friend %>
        <% end %>
    </tbody>
    <% end %>
  </table>
</div>

app/views/friends/new.html.erb
<h1>Add a friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="h-100 p-3 bg-light border rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-6 fw-bold">
      <%= @friend.first_name %> <%= @friend.last_name %>
    </h1>
    <br>
    <p>
      Email: <%= @friend.email %>
    </p>
    <hr>
    <p>
      Phone: <%= @friend.phone %>
    </p>
    <hr>
    <p>
      Instagram: <%= @friend.instagram %>
    </p>
    <hr>
    <p>
      Github: <%= @friend.github %>
    </p>
  </div>
</div>
<br>
<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary"%> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary"%>
  <hr>
  <%= button_to "Delete this friend", @friend, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
      </svg>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li> 

        <% end %>

      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">

        <% if user_signed_in? %>       

          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>

        <% end %>

      </ul>

<!--
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
-->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<div class="px-4 py-5 my-2 text-center">
    <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" fill="currentColor" class="bi bi-book d-block mx-auto mb-4" viewBox="0 0 16 16">
        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
    </svg>
    <h1 class="display-4 text-body-emphasis">Address Book</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Address Book is a simple example app built using Ruby on Rails. Featuring a robust login system powered by Devise and styled with Bootstrap, it allows users to maintain a personalized address book of friends</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <% if user_signed_in? %>
          <%= link_to "View My Address Book", friends_path, class:"btn btn-primary btn-lg px-4 gap-3" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary btn-lg px-4 gap-3" %>
          <%= link_to "Sign In", new_user_session_path, class:"btn btn-outline-secondary btn-lg px-4" %>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= render "home/header" %>
    <br>
    <div class='container'>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <br>
  </body>
</html>